title: Northern Blade Translations
tagline: NorthbladeTL
description: Free English Translations of Korean and Chinese Novels with no ads.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://northbladetl.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
markdown_ext: md
kramdown:  
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:title:output_ext
logo: /android-chrome-512x512.png
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true
archives:
  - enabled: true
    type: "paginated"
    layouts: "home"

turnstile_site_key: "0x4AAAAAABlBn5y8m8IJa-Vb"


# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives

jekyll-sitemap:
  exclude:
    - "SIMB/chapters/**"
    - "LNB/chapters/**"
    - "ABSW/chapters/**"
    - "HERO/chapters/**"