title: Northern Blade Translations
tagline: NorthbladeTL
description: We offer high-quality English fan translations of popular webnovels and novels, including Star Instructor Master Baek, Absolute Warrior, Legend of the Northern Blade, and Heroes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://northbladetl.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
markdown_ext: md
kramdown:  
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:title:output_ext
logo: /android-chrome-512x512.png

turnstile_site_key: "0x4AAAAAABlBn5y8m8IJa-Vb"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

jekyll-sitemap:
  exclude:
    - "SIMB/chapters/**"
    - "LNB/chapters/**"
    - "ABSW/chapters/**"
    - "HERO/chapters/**"